apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: super-dev-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - super-dev-app.example.com
    secretName: super-dev-app-tls
  rules:
  - host: super-dev-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: super-dev-app
            port:
              number: 80
